name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test ./tests/Example.Service.UnitTests --no-build --verbosity normal
      - name: Prepare for integration tests
        run: docker-compose up -d run-app
      - name: Wait for 5 seconds
        run: sleep 5s
        shell: bash
      - name: Run integration tests
        run: docker-compose run --rm component-tests
